// <auto-generated />
using System;
using HRM.API.Db;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HRM.API.Migrations
{
    [DbContext(typeof(HRMContext))]
    [Migration("20230724193826_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("HRM.API.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Designation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FathersName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MothersName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 10,
                            DateOfBirth = new DateTime(1984, 12, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Designation = "Head of Software Development",
                            FathersName = "Yeasin Bhuiyan",
                            MothersName = "Moriom Begum",
                            Name = "Md. Mahedee Hasan"
                        },
                        new
                        {
                            Id = 11,
                            DateOfBirth = new DateTime(1990, 10, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Designation = "Software Engineer",
                            FathersName = "Shahidul Islam",
                            MothersName = "Momtaz Begum",
                            Name = "Khaleda Islam"
                        },
                        new
                        {
                            Id = 12,
                            DateOfBirth = new DateTime(2017, 9, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Designation = "Jr. Software Engineer",
                            FathersName = "Md. Mahedee Hasan",
                            MothersName = "Khaleda Islam",
                            Name = "Tahiya Hasan Arisha"
                        },
                        new
                        {
                            Id = 13,
                            DateOfBirth = new DateTime(2021, 3, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Designation = "Jr. Software Engineer",
                            FathersName = "Md. Mahedee Hasan",
                            MothersName = "Khaleda Islam",
                            Name = "Humaira Hasan"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
