pipeline {
    agent any
    environment {
         IMAGE_REPO_NAME="C:\Jenkins_Demo\HRM\HRMJ\HRM.API\"
         IMAGE_TAG="v1"
         dotnet = 'C:\\Program Files\\dotnet\\dotnet.exe'   
    }
    stages {
        stage('Checkout Stage') {
            steps {
                git credentialsId: '8e3babfe-eb51-479e-b956-7a12427dc4e9', url: 'https://github.com/yalmaw/HRM.git', branch: 'master'
            }
        }
        stage('Build') {
            steps {
                 bat 'dotnet build C:\\Jenkins_Demo\\HRM\\HRMJ\\HRM.sln --configuration Release' 
            }
        }
        stage('Test') {  
            steps {  
               bat 'dotnet test C:\\Jenkins_Demo\\HRM\\hrmj\\UnitTest1\\UnitTest1.csproj --logger:trx' 
        }
        }
       
    stage('Building image') {
      steps{
        script {
          dockerImage = docker.build "${IMAGE_REPO_NAME}:${IMAGE_TAG}"
        }
      }
    }
  }
  }